---
- hosts: webservers
  become: true
  remote_user: vagrant
  tasks:

    - name: Install Tomcat 7
      apt: 'pkg={{item}} state=present'
      with_items:
        - openjdk-7-jre-headless
        - tomcat7

    - name: Get JRE path
      shell: ls -d /usr/lib/jvm/java-7* | tail -1
      register: jre_7_ls

    - name: Set JRE path
      set_fact: jre_7_path="{{jre_7_ls.stdout}}"

    - name: Unzip WAR file
      copy: src=/tmp/hello-world-war-1.0.0.war dest=/var/lib/tomcat7/webapps/ mode=0755 owner=tomcat7 group=tomcat7

    - name: xml file
      copy: src=/tmp/hello-world.xml dest=/var/lib/tomcat7/conf/Catalina/localhost/ mode=0755 owner=tomcat7 group=tomcat7

    - name: Restart tomcat7
      service: name=tomcat7 state=restarted
