---
- hosts: localhost
  user: root
  tasks:
    - name: Instalacao do apache
      action: apt pkg ={{ item }} state=installed
      with_items:
        - php5
        - apache2
        - mysql-server
        - mysql-client
        - php5-mysql
        - php-apc
        - php5-xmlrpc
        - php-soap
        - php5-gd
        - unzip
        - wget
        - python-mysqldb

    - name: Apache2 | Habilitando modulos
      action: command a2enmod rewrite vhosts_alias

    - name: Restart dos servicos
      action: service name=apache2 state=restarted
